baseURL: http://localhost/
# for xml output
languageCode: "de-at"
# for website
defaultContentLanguage: "de"
title: proMusica
# alternate copyright company text
copyright: proMusica
# languages
languages:
  de:
    contentDir: content/de
    languageName: Deutsch
    menu: main
    weight: 10
  en:
    contentDir: content/en
    languageName: English
    menu: main
    weight: 20
# controls number of pages displayed on list pages
paginate: 6
# controls the summary length on list pages
summaryLength: 7
# this is required so that Hugo will render markdown to HTML
markup:
  goldmark:
    renderer:
      unsafe: true
# taxonomy set up (tags have been disabled)
taxonomies:
  category: categories
params:
  slogan: Sound is our Passion

  # https://schema.org/Organization
  ## JSON-LD
  schemaType: "Organization"
    # schemaType: "Person"
  contact:
    # https://schema.org/PostalAddress
    address:
    # first record is for schema
    - name: Address
      streetAddress: 
      - Böcklinstrasse 100
      addressLocality: 1020 Wien
      addressRegion: 
      postalCode: 
      addressCountry: Austria
      # hasMap
      url: https://goo.gl/maps/ha3CkTm5muAP3KD9A
      geo: #coordinates 
      # icon: icons/bootstrap/geo-alt.svg
      icon: bi bi-geo-alt
      disable: false
    # postal address is just for contact details display
    # servicePostalAddress:
    #   postOfficeBoxNumber:
    #   addressLocality: Pyrmont
    #   addressRegion: NSW
    #   postalCode: 2009
    #   addressCountry: Australia

    openingHours:
    - name: Opening Hours
      # icon: icons/bootstrap/clock.svg
      icon: bi bi-clock
      hours:
      # date is ignored for display and schema
      - day: Montag
        open: 2021-01-01T14:00:00
        close: 2021-01-01T17:00:00
      - day: Dienstag
        open: 2021-01-01T09:00:00
        close: 2021-01-01T17:00:00
      - day: Mietwoch
        open: 2021-01-01T09:00:00
        close: 2021-01-01T17:00:00
      - day: Donnerstag
        open: 2021-01-01T09:00:00
        close: 2021-01-01T17:00:00
      - day: Freitag
        open: 2021-01-01T09:00:00
        close: 2021-01-01T17:00:00
      - day: Saturday/Sunday 
        custom:  Nach Vereinbarung
    telephone:
    # first record appears in schema data
    - name: Phone
      text: (0676) 777 4149
      url: "tel:+61280043293"
      # icon: icons/bootstrap/phone.svg
      icon: bi bi-phone
      disable: false
    # mobile
    # - text:
    #   url:
    #   icon: icons/bootstrap/telephone
    #   disable: false
    email: 
    - name: Email
      text: support@promusica.co
      url: "mailto:test@domain.com"
      # icon: icons/bootstrap/envelope.svg
      icon: bi bi-envelope
      disable: false
      desc: Email Address
  # only for contact details display
    extraItem:
    - name: Help Desk
      text: Help Desk
      url: helpdesk.com
      icon: 
      disable: true


  # founder:
  # foundingDate:
  # foundingLocation:
  # logo
