baseURL: http://localhost/
# for xml output
languageCode: "de-at"
# for website
defaultContentLanguage: "de"
title: proMusica
# alternate copyright company text
copyright: proMusica
# languages
languages:
  de:
    contentDir: content/de
    languageName: Deutsch
    menu:
      main:
      - identifier: serviceleistung
        name: Serviceleistung
        weight: 20
      - parent: serviceleistung
        weight: 40
        params:
          divider: true
      # - identifier: shop
      #   name: Shop
      #   weight: 60
      # - parent: shop
      #   weight: 40
      #   params:
      #     divider: true
  en:
    contentDir: content/en
    languageName: English
    menu: main
    weight: 20
  es:
    contentDir: content/es
    languageName: Español
    menu: main
    weight: 30
# controls number of pages displayed on list pages
paginate: 6
# controls the summary length on list pages
summaryLength: 40
# enables robots.txt
enableRobotsTXT: true
# remove all white spaces when minifying
minify:
    tdewolff:
      html:
        keepWhitespace: false

# this is required so that Hugo will render markdown to HTML
markup:
  goldmark:
    renderer:
      unsafe: true
# taxonomy set up (tags have been disabled)
taxonomies:
  category: categories
params:
  twitterSite: "@site_name"
  TwitterCreator: "@my_account"
  slogan: Sound is our Passion
  image:
    widths: 
      default: [400, 600, 800, 1200]
      shopSingle: [336, 456, 535, 700, 1000]

  # https://schema.org/Organization
  ## JSON-LD
  schemaType: "Organization"
    # schemaType: "Person"
  contact:
    # https://schema.org/PostalAddress
    address:
    # first record is for schema
    - name: Address
      streetAddress: 
      - Böcklinstrasse 100
      addressLocality: 1020 Wien
      addressRegion: 
      postalCode: 
      addressCountry: Austria
      # hasMap
      url: https://goo.gl/maps/ha3CkTm5muAP3KD9A
      geo: #coordinates 
      icon: icons/bootstrap/geo-alt.svg
      # icon: bi bi-geo-alt
      disable: false
    # postal address is just for contact details display
    # servicePostalAddress:
    #   postOfficeBoxNumber:
    #   addressLocality: Pyrmont
    #   addressRegion: NSW
    #   postalCode: 2009
    #   addressCountry: Australia

    openingHours:
    - name: Opening Hours
      icon: icons/bootstrap/clock.svg
      # icon: bi bi-clock
      hours:
      # date is ignored for display and schema
      - day: Montag
        open: 2021-01-01T14:00:00
        close: 2021-01-01T20:00:00
      - day: Dienstag
        open: T09:00:00
        close: T17:00:00
      - day: Mietwoch
        open: 2021-01-01T09:00:00
        close: 2021-01-01T17:00:00
      - day: Donnerstag
        open: 2021-01-01T09:00:00
        close: 2021-01-01T17:00:00
      - day: Freitag
        open: 2021-01-01T09:00:00
        close: 2021-01-01T17:00:00
      - day: Saturday/Sunday 
        custom:  Nach Vereinbarung
    telephone:
    # first record appears in schema data
    - name: Phone
      text: (0676) 777 4149
      url: "tel:+61280043293"
      icon: icons/bootstrap/telephone.svg
      # icon: bi bi-phone
      disable: false
    # mobile
    # - text:
    #   url:
    #   icon: icons/bootstrap/telephone
    #   disable: false
    email: 
    - name: Email
      text: support@promusica.co
      url: "mailto:test@domain.com"
      icon: icons/bootstrap/envelope.svg
      # icon: bi bi-envelope
      disable: false
      desc: Email Address
  # only for contact details display
    extraItem:
    - name: Help Desk
      text: Help Desk
      url: helpdesk.com
      icon: 
      disable: true


  # founder:
  # foundingDate:
  # foundingLocation:
  # logo

#     title: Serviceleistung
#     url: de/serviceleistung/
#     weight: 1
#   - identifier: gitarrenunterricht
#     name: Gitarrenunterricht
#     parent: serviceleistung
#     url: de/serviceleistung/gitarrenunterricht
#     weight: 2